In [2]:
#Import numpy as np and print the version number.Import numpy as np and print the version number.
import numpy as np
np.__version__

'1.18.1'

In [3]:
#Create a 1D array of numbers from 0 to 9Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Create a 3×3 numpy array of all True’s
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#Create a 3×3 numpy array of all True’s
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
#Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [9]:
#Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
#Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
#Convert a 1D array to a 2D array with 2 rows
np.arange(10)
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
#Stack arrays a and b vertically
a = [1,2,3,4]
b = [5,6,7,8]
np.vstack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#Stack arrays a and b horizontally
a = [1,2,3,4]
b = [5,6,7,8]
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
#Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [23]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [24]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [28]:
#Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [31]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [34]:
#Swap columns 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [35]:
#Swap rows 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr
arr[[1,0,2],: ]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [36]:
#Reverse the rows of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [37]:
#Reverse the columns of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [38]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10
arr = np.arange(9).reshape(3,3)
np.random.uniform(5,10,size=(5,3))

array([[9.7063069 , 5.34616634, 5.09839412],
       [6.97891083, 8.85673323, 7.29348736],
       [6.93883767, 5.50751671, 6.90694011],
       [6.74536563, 9.2474997 , 8.56929132],
       [8.22807467, 6.43374611, 6.18886473]])

In [42]:
#Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.random((5,3))
rand_arr
np.set_printoptions(precision=3)
rand_arr

array([[0.641, 0.244, 0.944],
       [0.171, 0.548, 0.712],
       [0.711, 0.627, 0.963],
       [0.798, 0.121, 0.239],
       [0.159, 0.491, 0.433]])

In [44]:
#Limit the number of items printed in python numpy array a to a maximum of 6 elements
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [49]:
# np.set_printoptions(threshold=6)
# np.arange(15)
# np.set_printoptions(threshold=np.nan)
# a

In [50]:
# Import the iris dataset keeping the text intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
+
# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [7]:
#Extract the text column species from the 1D iris imported in previous question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
species[:5]
species

(150,)


C:\Users\SANTOSH-PC\anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [8]:
#Convert the 1D iris to 2D array iris_2d by omitting the species text field.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

C:\Users\SANTOSH-PC\anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [12]:
#Find the mean,median, standard deviation of iris's sepallength (1st column)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength
np.mean(sepallength)
np.median(sepallength)
np.std(sepallength)

0.8253012917851409

In [13]:
#Q. Create a normalized form of iris's sepallength whose values range exactly 
#between 0 and 1 so that the minimum has value 0 and maximum has value 1.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
S

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [14]:
#Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))


[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

In [15]:
#Find the 5th and 95th percentile of iris's sepallength

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, [5,95])

array([4.6  , 7.255])

In [16]:
# Insert np.nan values at 20 random positions in iris_2d dataset

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)

In [17]:
# Find the number and position of missing values in iris_2d's sepallength (1st column)

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 4
Position of missing values: 
 (array([ 21,  38,  52, 147], dtype=int64),)


In [18]:
#Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [19]:
#Select the rows of iris_2d that does not have any nan value.

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [20]:
#Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

In [21]:
#Find out if iris_2d has any missing values.

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()
#> False

False

In [22]:
#Replace all ccurrences of nan with 0 in numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [23]:
#Find the unique values and the count of unique values in iris's species

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [25]:
#Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]


['small', 'small', 'small', 'small']

In [26]:
#Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(3,7)

array([3, 4, 5, 6])

In [4]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [5]:
x = np.array([1, 2, 3])

In [6]:
y = x

In [7]:
y

array([1, 2, 3])

In [8]:
z = np.copy(x)

In [9]:
z


array([1, 2, 3])

In [10]:
np.empty([2,2])

array([[1.14356149e-311, 1.33511562e-306],
       [1.69121775e-306, 1.69122046e-306]])

In [11]:
arr = np.array([1,2,3])

np.ones_like(arr)

array([1, 1, 1])

In [13]:
np.zeros_like(arr)

array([0, 0, 0])

In [14]:
np.empty_like(arr)

array([-359033664,        538,          0])

In [16]:
np.full_like(arr, 5)

array([5, 5, 5])

In [17]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linspace(2.0, 3.0, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [28]:
 x = np.array([1, 2, 2.5])
 x

array([1. , 2. , 2.5])

In [25]:
x.astype(int)

array([1, 2, 2])

In [35]:
x = np.array([[1, 2], [3, 4]])

In [36]:
m = np.asmatrix(x)

In [37]:
m [0,0] = 5

In [38]:
m

matrix([[5, 2],
        [3, 4]])

In [39]:
x =np.array([1,2,3])
np.cov(x)

array(1.)

In [40]:
 x = np.array([[0, 2], [1, 1], [2, 0]]).T

In [41]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

In [45]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [46]:
np.std(a)

1.118033988749895

In [47]:
np.var(a)

1.25

In [48]:
np.all([[True,False],[True,True]])

False

In [49]:
np.any([[True, False], [True, True]])

True

In [50]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])

In [51]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [52]:
a = np.arange(6).reshape(2,3)


In [53]:
a.argmax()

5

In [54]:
a.argmin()

0

In [55]:
x = np.array([3, 1, 2])

In [56]:
x.argsort()

array([1, 2, 0], dtype=int64)

In [57]:
x.max()

3

In [58]:
x.min()

1

In [ ]:
x

In [65]:
a = np.array([[1,4],[3,1]])

In [67]:
np.sort(a, axis =None)

array([1, 1, 3, 4])

In [68]:
np.sort(a, axis=0)  

array([[1, 1],
       [3, 4]])

In [69]:
a = np.array([1,2,3])

In [70]:
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [71]:
np.cumsum(a)

array([1, 3, 6], dtype=int32)

In [73]:
np.prod(a)

6

In [75]:
np.sum(a)

6

In [78]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [77]:
 np.ptp(x, axis=0)

array([2, 2])

In [79]:
 np.ptp(x, axis=1)

array([1, 1])

In [80]:
x = np.arange(10)

In [82]:
np.where(x>5)

(array([6, 7, 8, 9], dtype=int64),)